version: "3.8"
services:
  server:
    build: .
    container_name: server
    ports:
      - "${HTTP_PORT}:8000"
    volumes:
      - ./:/var/www/
      - /var/www/vendor
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql
  client:
      build:
        context: .
        dockerfile: ./../client/shippers/Dockerfile.node
      container_name: client
      volumes:
        - ./:/var/www/
        - /var/www/node_modules
      depends_on:
        - "server"
volumes:
    mysql_data:



# =============
# version: '3.8'
# services: 
#     mysql:
#       platform: linux/x86_64
#       image: mysql:8.0
#       command: --default-authentication-plugin=mysql_native_password
#       environment:
#         MYSQL_DATABASE: ${DB_DATABASE}
#         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#         MYSQL_ALLOW_EMPTY_PASSWORD: true
#         MYSQL_HOST: ${DB_HOST}
#         MYSQL_PORT: ${DB_PORT}
#         MYSQL_USERNAME: root
#       ports:
#         - ${DB_PORT}:3306
#       volumes:
#         - ./mysql/init.sql:/data/application/init.sql
#         - mysql_data:/var/lib/mysql
#     server:
#         build: 
#             context: .
#             dockerfile: Dockerfile
#         command: 'php artisan serve --host=0.0.0.0'
#         volumes:
#             - .:/app
#         ports:
#             - 8000:8000
#         depends_on:
#           - mysql
#     queue:
#       build:
#         context: .
#         dockerfile: Dockerfile
#       command: 'php artisan queue:work'
#       depends_on:
#         - mysql
    
# volumes:
#   mysql_data:



# DBBBB

# DB_CONNECTION=mysql
# DB_HOST=mysql
# DB_PORT=3306
# DB_DATABASE=booking_db
# DB_USERNAME=root
# DB_PASSWORD=